# Generated by Django 6.0.4 on 2026-04-22 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(editable=False, max_length=100, unique=True)),
                ('sender_name', models.CharField(max_length=100)),
                ('receiver_name', models.CharField(max_length=100)),
                ('source_pincode', models.CharField(max_length=10)),
                ('destination_pincode', models.CharField(max_length=10)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dimensions', models.CharField(blank=True, max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('CONFIRMED', 'Confirmed'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered')], default='CREATED', max_length=50)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
