# Generated by Django 6.0.4 on 2026-04-23 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0002_parcel_assigned_delivery_staff_parcel_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='receiver_phone',
            field=models.CharField(default='0000000000', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parcel',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
