# Generated by Django 6.0.4 on 2026-04-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0002_parcel_assigned_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='parcel_id',
            field=models.CharField(editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered')], default='CREATED', max_length=50),
        ),
    ]
