# Generated by Django 6.0.4 on 2026-04-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0002_alter_parcel_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='status',
            field=models.CharField(default='CREATED', max_length=50),
        ),
    ]
