# Generated by Django 6.0.4 on 2026-04-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0003_parcel_receiver_phone_alter_parcel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='sender_phone',
            field=models.CharField(default='0000000000', max_length=15),
            preserve_default=False,
        ),
    ]
