# Generated by Django 6.0.4 on 2026-04-20 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0003_parcel_price_parcel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('CONFIRMED', 'Confirmed'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered')], default='CREATED', max_length=50),
        ),
    ]
