# Generated by Django 6.0.4 on 2026-04-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0003_parcel_parcel_id_alter_parcel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='parcel_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='tracking_id',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, unique=True),
        ),
    ]
