# Generated by Django 6.0.4 on 2026-04-23 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('parcel', '0004_alter_parcel_parcel_id_alter_parcel_tracking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='assigned_delivery_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_parcels', to='accounts.staff'),
        ),
    ]
