# Generated by Django 6.0.4 on 2026-04-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0005_parcel_otp_created_at_alter_parcel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='receiver_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
