# Generated by Django 6.0.4 on 2026-04-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='eta_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
