# Generated by Django 6.0.4 on 2026-04-20 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_location_district_location_state_tracking_updated_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='district',
        ),
        migrations.RemoveField(
            model_name='location',
            name='state',
        ),
        migrations.RemoveField(
            model_name='tracking',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='tracking',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('PICKED', 'Picked Up'), ('TRANSIT', 'In Transit'), ('ARRIVED', 'Arrived at Hub'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered')], max_length=30),
        ),
    ]
