# Generated by Django 6.0.4 on 2026-04-21 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_location_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
